frontend:
  autoscaling:
    averageUtilization: 55

backend:
  autoscaling:
    averageUtilization: 44

database:
  enabled: true
  uri: 10.10.10.10
  username: external_postgres
  password: external_postgres
