backend:
  image: walk1ng/backend
  tag: latest
  autoscaling:
    averageUtilization: 90

frontend:
  image: walk1ng/frontend
  tag: latest
  autoscaling:
    averageUtilization: 90

database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
